
global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api-service:8000"]
  - job_name: "telemetry"
    static_configs:
      - targets: ["telemetry-service:8000"]
  - job_name: "analytics"
    static_configs:
      - targets: ["analytics-service:8000"]
